import json
import logging
from datetime import datetime, timezone
from pathlib import Path

from freqtrade.strategy import IStrategy
from pandas import DataFrame

logger = logging.getLogger(__name__)


class SignalStrategy(IStrategy):
    """
    Phase 6: Freqtrade strategy acting purely as an execution shell.
    Reads the deterministic signal JSON generated by the Research Plane.
    Does NOT contain any AI inference, TimesFM calls, or LLM code.
    """

    INTERFACE_VERSION = 3

    # Define minimal ROI and stoploss. Real risk management is done by the Governor.
    minimal_roi = {
        "0": 100.0  # Let the signal logic handle exits
    }
    stoploss = -0.99  # Large stoploss, let the strategy exit via signal

    timeframe = '1m'
    process_only_new_candles = False

    def __init__(self, config: dict) -> None:
        super().__init__(config)
        # Using the standard data/signals path from architecture
        self.signal_file = Path("data/signals/latest_signal.json")

    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        # All indicator logic is in the Research Plane
        return dataframe

    def _read_signal(self) -> dict | None:
        if not self.signal_file.exists():
            return None
        try:
            with open(self.signal_file, "r") as f:
                signal = json.load(f)
            
            # Check expiration
            expires_at = datetime.fromisoformat(signal["expires_at"])
            if datetime.now(timezone.utc) > expires_at:
                return None
                
            return signal
        except Exception as e:
            logger.error(f"Failed to read signal: {e}")
            return None

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[:, 'enter_long'] = 0
        dataframe.loc[:, 'enter_short'] = 0

        signal = self._read_signal()
        if not signal:
            return dataframe

        symbol = metadata["pair"].replace("/", "")
        if signal["symbol"] != symbol:
            return dataframe

        if signal["action"] == "open" and signal["side"] == "long":
            dataframe.loc[dataframe.index[-1], 'enter_long'] = 1

        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        dataframe.loc[:, 'exit_long'] = 0
        dataframe.loc[:, 'exit_short'] = 0

        signal = self._read_signal()
        if not signal:
            return dataframe

        symbol = metadata["pair"].replace("/", "")
        if signal["symbol"] != symbol:
            return dataframe

        if signal["action"] == "close":
            dataframe.loc[dataframe.index[-1], 'exit_long'] = 1

        return dataframe
